export interface HmtsPending {
    id: number;
    countryOfOrigin: string;
    licensedCountry: string;
    levelOfService: string;
    subcity: string;
    district: string;
    kebele: string;
    specificArea: string;
    passportNo: string;
    phoneNumber: string;
    email: string;
    manufacturerSerial: string;
    isFirearm: boolean;
    dateMarked: Date;
    markedBy: string;
    firearmType: string;
    firearmModel: string;
    firearmMechanism: string;
    firearmCalibre: string;
    magazineCapacity: string;
    manufacturer: string;
    yearManufacture: Date;
    source: string;
    store: string;
    additionalComment: string;
    registeredPosition: string;
    registeredFullName: string;
    registeredTitle: string;
    registeredResponsibility: string;
    registeredSignature: string;
    registeredDate: Date;
    registeredBodyFullName: string;
    registeredBodyResponsibility: string;
    registeredBodySignature: string;
    registeredBodyDate: Date;
    holder: string;
  }
  