export interface User {
    firstname: string,
        middlename: string,
        lastname: string,
        efpid: string,
        job: string,
        jobtype: string,
        unit: string,
        organization: string,
        telephone: string,
        extension : string,
        mobile : string,
        email : string,
        address : string,
        town : string,
        country: string,
        accounttype : string,
        Loginicon: string,
        username : string,
        status : string,
        password: string,
}